### ISSUE TITLE
気になったことを言うだけのissue

### ISSUE THREAD

**Issue by osakana11011** [kuri-megane/pac-man-game#1]

**Comment by osakana11011** [comment]
少し動かしてみて、敵が通った後にクッキーが無くなるのは仕様🤔？
本家だとクッキーは無くならないから。

**Comment by kuri-megane** [comment]
そういうことにしたうん

**Comment by osakana11011** [comment]
これは、`Game.java`の中で`pacMan`や`monster`のインスタンスを使いたくて後から追加していると思うんだけど、
https://github.com/kuri-megane/pac-man-game/blob/045ade6f0642d7dcd191e72ee3b6599af4cbcbfc/src/main/java/io/github/kuri_megane/Game.java#L28-L33

`GameMap.java`のここに"p"や"m"を置いて初期化した方がイイ気がする。
`convert`で変換してくれる仕組みもあるし、今のままだと、例えば`Point(1,2)`に壁があったらバグるから怖い🤔
https://github.com/kuri-megane/pac-man-game/blob/045ade6f0642d7dcd191e72ee3b6599af4cbcbfc/src/main/java/io/github/kuri_megane/Objects/GameMap.java#L36-L42

でもそれだと、`pacMan`のインスタンスが取れないから、`GameMap`クラスに`getPacMan`、`getMonsters`なるものを用意して取り出せるようにするとかしなきゃいけないけど。

今回っきりならそれでもイイかもしれないけど一応...。

**Comment by osakana11011** [comment]
たぶん本来なら、ここの`goFlag`は`false`だと思われ。
今は`Controller.move`で制御してるからバグってないけど、`Controller.move`変更したらバグる可能性あるから注意。
https://github.com/kuri-megane/pac-man-game/blob/045ade6f0642d7dcd191e72ee3b6599af4cbcbfc/src/main/java/io/github/kuri_megane/Objects/Wall.java#L9

**Comment by kuri-megane** [comment]
> これは、`Game.java`の中で`pacMan`や`monster`のインスタンスを使いたくて後から追加していると思うんだけど、
> https://github.com/kuri-megane/pac-man-game/blob/045ade6f0642d7dcd191e72ee3b6599af4cbcbfc/src/main/java/io/github/kuri_megane/Game.java#L28-L33
> 
> `GameMap.java`のここに"p"や"m"を置いて初期化した方がイイ気がする。
> `convert`で変換してくれる仕組みもあるし、今のままだと、例えば`Point(1,2)`に壁があったらバグるから怖い🤔

最初そうしてたんだけど，

> でもそれだと、`pacMan`のインスタンスが取れないから、`GameMap`クラスに`getPacMan`、`getMonsters`なるものを用意して取り出せるようにするとかしなきゃいけないけど。

そうそうそれが必要だと思って今の形に変えたんだよね
monster複数配置したい事もあって,設計が悪かった
保留かなぁ

**Comment by kuri-megane** [comment]
> たぶん本来なら、ここの`goFlag`は`false`だと思われ。
> 今は`Controller.move`で制御してるからバグってないけど、`Controller.move`変更したらバグる可能性あるから注意。
> https://github.com/kuri-megane/pac-man-game/blob/045ade6f0642d7dcd191e72ee3b6599af4cbcbfc/src/main/java/io/github/kuri_megane/Objects/Wall.java#L9

これはミスだわ！直します．

**Comment by osakana11011** [comment]
> そうそうそれが必要だと思って今の形に変えたんだよね
> monster複数配置したい事もあって,設計が悪かった
> 保留かなぁ

うーん、俺はこの設計でイイと思ってるけどなー🤔
`monster`を複数設置するとしたら、`GameMap.getMonsters`で`List<Point>`を返すようにして、`monster`の移動もそのリストに対してループ回せばイイかなと。

**Comment by osakana11011** [comment]
あとは、敵の動きについて、今は完全ランダムで、確率的に初期位置に停滞しがちになるのが気になるかな。

よりゲーム性を高めたいなら幅優先探索でプレイヤーを追うようにできたらすごく良さそう。
(割と実装重いです。)

それがキツいのなら、敵が移動した時に**どこから移動してきたのか**っていう情報を保持しておいて、次移動する時に移動してきたマスへ戻る確率を減らすようにするだけでも、敵が初期位置に停滞する確率が下がってゲーム性が出てくると思う。

**Comment by osakana11011** [comment]
後は、使われていない変数が所々あったり、publicメソッドでprivateに直せる所があるのが気になります。

以上です。

**Comment by kuri-megane** [comment]
> > そうそうそれが必要だと思って今の形に変えたんだよね
> > monster複数配置したい事もあって,設計が悪かった
> > 保留かなぁ
> 
> うーん、俺はこの設計でイイと思ってるけどなー🤔
> `monster`を複数設置するとしたら、`GameMap.getMonsters`で`List<Point>`を返すようにして、`monster`の移動もそのリストに対してループ回せばイイかなと。

(これ読む前に)
初めて配置するときの変数を別に設けて，チェックするように変えてみたわ
時間あればこの実装に変えたいと思う

**Comment by kuri-megane** [comment]
> あとは、敵の動きについて、今は完全ランダムで、確率的に初期位置に停滞しがちになるのが気になるかな。
> 
> よりゲーム性を高めたいなら幅優先探索でプレイヤーを追うようにできたらすごく良さそう。
> (割と実装重いです。)
> 
> それがキツいのなら、敵が移動した時に**どこから移動してきたのか**っていう情報を保持しておいて、次移動する時に移動してきたマスへ戻る確率を減らすようにするだけでも、敵が初期位置に停滞する確率が下がってゲーム性が出てくると思う。

確かになんか停滞してるなぁって思ってた
うまく参考にしてみる
